- karaf-features/src/main/resources/features.xml
- plugin/src/main/java/org/opennms/velocloud/connections/Connection.java
- plugin/src/main/java/org/opennms/velocloud/connections/ConnectionManager.java
- plugin/src/main/java/org/opennms/velocloud/connections/ConnectionValidationError.java
- plugin/src/main/java/org/opennms/velocloud/requisition/AbstractRequisitionProvider.java
- plugin/src/main/java/org/opennms/velocloud/requisition/CustomerRequisitionProvider.java
- plugin/src/main/java/org/opennms/velocloud/requisition/PartnerRequisitionProvider.java
- plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
Implementation of a connection manager using SCV and usage in the requisition providers.
> NMS-14772: Implement connection manager

- client/api/src/main/java/org/opennms/velocloud/client/api/model/Edge.java
- client/api/src/main/java/org/opennms/velocloud/client/api/model/Link.java
- client/v1/src/main/java/org/opennms/velocloud/client/v1/VelocloudApiCustomerClientV1.java
- plugin/src/main/java/org/opennms/velocloud/requisition/AbstractRequisitionProvider.java
- plugin/src/main/java/org/opennms/velocloud/requisition/CustomerRequisitionProvider.java
JIRA Issue: https://issues.opennms.org/browse/NMS-14596
> NMS-14596: Import customer edges and links into a requisition

- client/v1/src/main/java/org/opennms/velocloud/client/v1/VelocloudApiCustomerClientV1.java
* JIRA: https://issues.opennms.org/browse/NMS-14981
> NMS-14981: Use recentLinks instead of links

- .gitignore
- DOCS.md
- docs/antora.yml
- docs/modules/ROOT/assets/images/.readme
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/index.adoc
- docs/modules/about/assets/images/.readme
- docs/modules/about/pages/introduction.adoc
- docs/modules/about/pages/terminology.adoc
- docs/modules/install/assets/images/.readme
- docs/modules/install/pages/requirements.adoc
- local-site.yml
* JIRA: https://issues.opennms.org/browse/NMS-15083
> NMS-15083: Added basic Antora file structure

- plugin/src/main/java/org/opennms/velocloud/pollers/AbstractStatusPoller.java
- plugin/src/main/java/org/opennms/velocloud/pollers/link/LinkConnectionStatusPoller.java
- plugin/src/main/java/org/opennms/velocloud/requisition/CustomerRequisitionProvider.java
- plugin/src/main/resources/poller-configuration.xml
https://issues.opennms.org/browse/NMS-14979
> NMS-14979: Fix service naming

- client/api/src/main/java/org/opennms/velocloud/client/api/model/Edge.java
- client/api/src/main/java/org/opennms/velocloud/client/api/model/Path.java
- client/v1/src/main/java/org/opennms/velocloud/client/v1/VelocloudApiCustomerClientV1.java
- docs/modules/operation/pages/service-assurance.adoc
- plugin/src/main/java/org/opennms/velocloud/pollers/path/PathStatusPoller.java
- plugin/src/main/java/org/opennms/velocloud/pollers/path/PathStatusPollerFactory.java
- plugin/src/main/java/org/opennms/velocloud/requisition/CustomerRequisitionProvider.java
- plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- plugin/src/main/resources/poller-configuration.xml
* JIRA: https://opennms.atlassian.net/browse/NMS-15228
> NMS-15228: Added monitor for edge path status

- client/api/src/main/java/org/opennms/velocloud/client/api/VelocloudApiCustomerClient.java
- client/api/src/main/java/org/opennms/velocloud/client/api/VelocloudApiPartnerClient.java
- client/v1/src/build/resources/swagger-5.0.0-dist.json
- client/v1/src/main/java/org/opennms/velocloud/client/v1/VelocloudApiCustomerClientV1.java
- client/v1/src/main/java/org/opennms/velocloud/client/v1/VelocloudApiPartnerClientV1.java
- client/v2/src/main/java/org/opennms/velocloud/client/v2/VelocloudApiPartnerClientV2.java
- docs/modules/operation/pages/service-assurance.adoc
- docs/modules/reference/pages/endpoints.adoc
- plugin/src/main/java/org/opennms/velocloud/connections/ConnectionManager.java
- plugin/src/main/java/org/opennms/velocloud/events/VelocloudEventIngestor.java
- plugin/src/main/java/org/opennms/velocloud/pollers/AbstractStatusPoller.java
- plugin/src/main/java/org/opennms/velocloud/pollers/edge/AbstractEdgeStatusPoller.java
- plugin/src/main/java/org/opennms/velocloud/pollers/edge/EdgeConnectionStatusPoller.java
- plugin/src/main/java/org/opennms/velocloud/pollers/edge/EdgeManagementStatusPoller.java
- plugin/src/main/java/org/opennms/velocloud/pollers/edge/EdgeManagementStatusPollerFactory.java
- plugin/src/main/java/org/opennms/velocloud/pollers/edge/EdgeServiceStatusPoller.java
- plugin/src/main/java/org/opennms/velocloud/requisition/AbstractRequisitionProvider.java
- plugin/src/main/java/org/opennms/velocloud/requisition/CustomerRequisitionProvider.java
- plugin/src/main/java/org/opennms/velocloud/requisition/PartnerRequisitionProvider.java
- plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- plugin/src/main/resources/poller-configuration.xml
* JIRA: https://opennms.atlassian.net/browse/VP-44
> VP-44: Added false-positive Edge status check

- docs/modules/configuration/pages/requisitions.adoc
- plugin/src/main/java/org/opennms/velocloud/requisition/AbstractRequisitionProvider.java
- plugin/src/main/java/org/opennms/velocloud/requisition/CustomerRequisitionProvider.java
- plugin/src/main/java/org/opennms/velocloud/requisition/PartnerRequisitionProvider.java
* JIRA: https://opennms.atlassian.net/browse/VP-59
> VP-59: Allow to set foreignSource for requisitions

- client/api/src/main/java/org/opennms/velocloud/client/api/VelocloudApiCustomerClient.java
- client/api/src/main/java/org/opennms/velocloud/client/api/model/Datacenter.java
- client/api/src/main/java/org/opennms/velocloud/client/api/model/Tunnel.java
- client/v1/src/build/resources/swagger-5.0.0-dist.json
- client/v1/src/main/java/org/opennms/velocloud/client/v1/VelocloudApiCustomerClientV1.java
- client/v1/src/test/java/org/opennms/velocloud/client/v1/VelocloudApiClientV1Test.java
- docs/modules/operation/pages/service-assurance.adoc
- plugin/src/main/java/org/opennms/velocloud/pollers/tunnel/DataCenterServicesStatusPoller.java
- plugin/src/main/java/org/opennms/velocloud/pollers/tunnel/DataCenterServicesStatusPollerFactory.java
- plugin/src/main/java/org/opennms/velocloud/pollers/tunnel/TunnelStatusPoller.java
- plugin/src/main/java/org/opennms/velocloud/requisition/CustomerRequisitionProvider.java
- plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
- plugin/src/main/resources/poller-configuration.xml
* JIRA: https://opennms.atlassian.net/browse/VP-17
> VP-17: Added poller for tunnels and data center services

- client/api/src/main/java/org/opennms/velocloud/client/api/VelocloudApiCustomerClient.java
- client/api/src/main/java/org/opennms/velocloud/client/api/model/CloudService.java
- client/v1/src/build/resources/swagger-5.0.0-dist.json
- client/v1/src/main/java/org/opennms/velocloud/client/v1/VelocloudApiCustomerClientV1.java
- plugin/src/main/java/org/opennms/velocloud/pollers/tunnel/TunnelStatusPoller.java
- plugin/src/main/java/org/opennms/velocloud/requisition/CustomerRequisitionProvider.java
- plugin/src/main/resources/poller-configuration.xml
* JIRA: https://opennms.atlassian.net/browse/VP-61
> VP-61: Changed the way tunnels are gathered and checked

- pom.xml
Adding a couple of properties to the main `pom.xml` file
> NMS-15512: Add the missing entries to pom.xml file

- plugin/src/main/java/org/opennms/velocloud/connections/ConnectionManager.java
- plugin/src/main/java/org/opennms/velocloud/requisition/AbstractRequisitionProvider.java
- plugin/src/main/java/org/opennms/velocloud/requisition/CustomerRequisitionProvider.java
- plugin/src/main/java/org/opennms/velocloud/requisition/PartnerRequisitionProvider.java
- pom.xml
* JIRA: https://opennms.atlassian.net/browse/VP-65
I've been looking for days to see where we made the mistake and finally - while investigating another issue - I realize it's a bug in Jersey that was fixed with a newer version. With the newer version everything works as it should.
> VP-65: Bumped version for jersey

- assembly/kar/pom.xml
Add plugin version to the KAR filename
> VP-68: add plugin version to the KAR filename

- karaf-features/src/main/resources/features.xml
This fixes loading on Horizon (core).
> VP-74: add jdk8 datatype

- karaf-features/src/main/resources/features.xml
* JIRA: https://opennms.atlassian.net/browse/VP-79
> VP-79: Fixed installation of plugin

- client/v1/src/test/java/org/opennms/velocloud/client/v1/VelocloudApiClientV1Test.java
- pom.xml
* JIRA: https://opennms.atlassian.net/browse/VP-84
> VP-84: Bumped Karaf plugin version

- README.md
- docs/modules/about/pages/introduction.adoc
- docs/modules/configuration/pages/connections.adoc
- docs/modules/configuration/pages/requisitions.adoc
- docs/modules/installation/pages/installation.adoc
- docs/modules/operation/pages/event-polling.adoc
- docs/modules/reference/pages/config-properties.adoc
- docs/modules/reference/pages/endpoints.adoc
- docs/modules/reference/pages/shell-commands.adoc
(Note this has changes from #60 and should be merged after that one is done)
https://opennms.atlassian.net/browse/VP-81
> VP-81: Docs: Expand differences between partner and customer connections

- docs/modules/operation/pages/service-assurance.adoc
Update documentation about what the various service monitors do.
https://opennms.atlassian.net/browse/VP-85
> VP-85: Docs update service descriptions

- client/v1/src/main/java/org/opennms/velocloud/client/v1/VelocloudApiCustomerClientV1.java
- client/v1/src/test/java/org/opennms/velocloud/client/v1/VelocloudApiClientV1Test.java
- pom.xml
* JIRA: https://opennms.atlassian.net/browse/VP-83
> VP-83: Downgrading Karaf version

- plugin/src/main/java/org/opennms/velocloud/pollers/path/PathStatusPoller.java
* JIRA: https://opennms.atlassian.net/browse/VP-86
> VP-86: Fixed logic of PathStatusPoller
